save_real_img: true

save_generated_img: true

max_pages: 1000 # Maximum number of pages of gallery to scrape per type of plate

countries:
  - al #Albania
  - ad #Andorra
  - ar #Argentina
  - am #Armenia
  - au #Australia
  - at #Austria
  - az #Azerbaijan
  - bh #Bahrain
  - by #Belarus
  - be #Belgium
  - ba #Bosnia and Herzegovina
  - br #Brazil
  - bg #Bulgaria
  - kh #Cambodia
  - ca #Canada
  - cn #China
  - hr #Croatia
  - cy #Cyprus
  - cz #Czech Republic
  - dk #Denmark
  - eg #Egypt
  - ee #Estonia
  - fi #Finland
  - fr #France
  - ge #Georgia
  - de #Germany
  - gi #Gibraltar
  - gr #Greece
  - gg #Guernsey
  - hk #Hong Kong
  - hu #Hungary
  - is #Iceland
  - id #Indonesia
  - ir #Iran
  - iq #Iraq
  - ie #Ireland
  - il #Israel
  - it #Italy
  - jp #Japan
  - je #Jersey
  - kz #Kazakhstan
  - kg #Kyrgyzstan
  - lv #Latvia
  - li #Liechtenstein
  - lt #Lithuania
  - lu #Luxembourg
  - my #Malaysia
  - mt #Malta
  - mx #Mexico
  - md #Moldova
  - mc #Monaco
  - mn #Mongolia
  - me #Montenegro
  - ma #Morocco
  - nl #Netherlands
  - nz #New Zealand
  - mk #North Macedonia
  - no #Norway
  - ps #Palestinian Authority
  - pl #Poland
  - pt #Portugal
  - qa #Qatar
  - ro #Romania
  - ru #Russia
  - sm #San Marino
  - sa #Saudi Arabia
  - rs #Serbia
  - sg #Singapore
  - sk #Slovakia
  - si #Slovenia
  - kr #South Korea
  - es #Spain
  - se #Sweden
  - ch #Switzerland
  - tj #Tajikistan
  - th #Thailand
  - tr #Turkey
  - ae #UAE
  - us #USA
  - su #USSR
  - ua #Ukraine
  - uk #United Kingdom
  - uz #Uzbekistan
  - vn #Vietnam
  - ax #Åland
  - xx #Non-recognized and partially recognized states